stages:
  - build
  - push

variables:
  IMAGE_NAME: soufian1/signatureapp
  DOCKER_DRIVER: overlay2

services:
  - docker:20.10.12-dind

before_script:
  - docker info
  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin

build:
  stage: build
  image: docker:20.10.12
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA .
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHORT_SHA $IMAGE_NAME:latest
  cache:
    key: docker-cache
    paths:
      - .docker/cache/

push:
  stage: push
  image: docker:20.10.12
  script:
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest
  only:
    - main