version: "3.8"

services:
  mongodb:
    image: mongo:6.0-jammy
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: express_app
    restart: always
    environment:
      - SECRET_KEY=your_secret_key_here
      - PORT=5000
      - MONGO_URI=mongodb://admin:secret@mongodb:27017/signatureapp?authSource=admin
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongo_data: